### ISSUE TITLE
font italic is creating another name 

### ISSUE THREAD

**Issue by llmdev** [sainnhe/icursive-nerd-font#3]
![image](https://user-images.githubusercontent.com/25234963/83816417-ba5b3200-a698-11ea-8e68-8c30561a9bc5.png)

Hello, font italic is creating another name not in the fira code group.

When I select Fira code it doesn't work in vscode or in the terminal

**Comment by sainnhe** [comment]
Looks like the renaming is failed. Try [this](https://drive.google.com/folderview?id=1BHoSCLDQL9X8qIowPBGBInKku6BLqVmL).

**Comment by llmdev** [comment]
Thx

**Comment by llmdev** [comment]
@sainnhe 
Can you help me ? On windows it worked fine but on mac it doesn't work .. follow the prints

Vscode
![image](https://user-images.githubusercontent.com/25234963/83894968-6730c000-a728-11ea-976f-27c838baeb74.png)

Iterm2
![image](https://user-images.githubusercontent.com/25234963/83895005-757edc00-a728-11ea-9219-a8be98c8681e.png)

**Comment by llmdev** [comment]
![image](https://user-images.githubusercontent.com/25234963/83896920-4322ae00-a72b-11ea-8ac7-3d6818bd27d8.png)
Font italic name => Book Italic

**Comment by sainnhe** [comment]
I have no idea what's happening, maybe you need to debug by yourself. Try commands like `fc-scan`, `fc-list`, etc.

Btw, I'm using alacritty and it works fine.

**Comment by llmdev** [comment]
friend, I decided to use alacritty and it worked here thanks
